### ISSUE TITLE
GPClaimExpiration WARN

### ISSUE THREAD

**Issue by SrBedrock** [GPAddons/GPClaimExpiration#18]
`[16:22:14] [Server thread/WARN]: [GPClaimExpiration] "GPClaimExpiration v1.0.0" has registered a listener for me.ryanhamshire.GriefPrevention.events.ClaimModifiedEvent on method "private void com.github.gpaddons.gpclaimexpiration.listener.ModernWarningListener.onClaimResize(me.ryanhamshire.GriefPrevention.events.ClaimResizeEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [${project.developers[0].name}].`

**Comment by Jikoo** [comment]
I need to fix this on the GP end - GPCE is listening to the correct event. TechFortress/GriefPrevention#1791

**Comment by enigma072485** [comment]
Just wondering....But is this issue still being looked into? I'm still seeing that error....would be nice if it was not there. If it's something I can ignore tho.....then so be it. Everything still works beautifully... :D
