### ISSUE TITLE
Option to warn player on claim creation

### ISSUE THREAD

**Issue by antcro74** [GPAddons/GPClaimExpiration#2]
It would be nice to warn players when they create a claim.

Ex: "Warning: this claim will expire after XX days of inactivity"

Also when claims are being transferred with changeClaimOwner (for RealEstate plugins)

**Comment by Jikoo** [comment]
Would also need to re-check to see if time had changed on resize. Definitely a good feature.

**Comment by Jikoo** [comment]
Partially implemented in afaf700, not possible to warn on transfer because there is no event for it.

**Comment by antcro74** [comment]
Awesome, thanks, I modified the plugins that used changeClaimOwner to warn the player. But yeah an event for that could definitely be great
