### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by ByFate644** [GPAddons/GPClaimExpiration#6]
hello my friend, how can I use the addon I don't understand anything because it is not in jar, it is hard to understand when it is bad in English.

**Comment by Jikoo** [comment]
Dev builds can be found [on the CI](https://ci.appveyor.com/project/Jikoo/gpclaimexpiration) in the artifacts tab. I have yet to tag a full release.

**Comment by ByFate644** [comment]
how do i convert it to plugin

**Comment by Jikoo** [comment]
Open link, navigate to artifacts tab, download GPClaimExpiration.jar

**Comment by ByFate644** [comment]
Thank you very much man.
